import os
import glob

def get_source_folders(base_src_dir):
    """
    Automatically discover all subdirectories in the base source directory.
    """
    src_folders = []
    if not os.path.exists(base_src_dir):
        print(f"Warning: Source directory '{base_src_dir}' does not exist!")
        return src_folders
    
    for item in os.listdir(base_src_dir):
        item_path = os.path.join(base_src_dir, item)
        if os.path.isdir(item_path):
            src_folders.append(item_path)
    
    return sorted(src_folders)

def create_unity_c_file(base_src_dir="new_new_src", source_directory=".", output_filename="unity.c"):
    """
    Create a unity.c file that includes all .c files from subdirectories.
    """
    src_folders = get_source_folders(base_src_dir)
    
    if not src_folders:
        print(f"No subdirectories found in '{base_src_dir}'")
        return False
    
    print(f"Found source folders: {[os.path.basename(folder) for folder in src_folders]}")
    
    c_files = []
    for folder in src_folders:
        glob_pattern = os.path.join(source_directory, folder, "*.h")
        folder_c_files = glob.glob(glob_pattern)
        c_files.extend(folder_c_files)
        # glob_pattern = os.path.join(source_directory, folder, "*.h")
        # folder_c_files = glob.glob(glob_pattern)
        # c_files.extend(folder_c_files)
        print(f"  {os.path.basename(folder)}: {len(folder_c_files)} .h files")
    
    print(f"Creating {output_filename}...")
    with open(output_filename, "w") as f_out:
        f_out.write("// This file is generated by the Python unity build script.\n")
        f_out.write("// Do not edit manually.\n\n")
        f_out.write("#define IMPL_\n\n")
        for c_file in c_files:
            relative_path = os.path.relpath(c_file, start=source_directory).replace(os.path.sep, '/')
            f_out.write(f'#include "{relative_path}"\n')
    
    print(f"Successfully created '{output_filename}' with {len(c_files)} '.h' files included.")
    return True


def main():
    """
    Main function to generate both unity.c and build.bat files.
    """
    base_src_dir = "src"  # Change this if your source directory has a different name
    
    print("=== Unity Build Generator ===")
    print(f"Scanning source directory: {base_src_dir}")
    
    # Create unity.c file
    unity_success = create_unity_c_file(base_src_dir)
    
    print()
    

if __name__ == "__main__":
    main()